FROM mongo:latest

VOLUME mongodb-data

# Update MongoDB configuration file to allow connections from other containers
RUN echo "bind_ip_all=true" >> /etc/mongodb.conf

# Expose the necessary port for your MongoDB instance
EXPOSE 27017

CMD ["mongod", "--config", "/etc/mongodb.conf"]